# Generated by Django 3.0.7 on 2020-09-02 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sw_catalog', '0002_auto_20200902_1310'),
        ('sw_cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitemattribute',
            name='price',
            field=models.FloatField(default=0, verbose_name='Ціна'),
        ),
        migrations.AlterField(
            model_name='cartitemattribute',
            name='value',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_item_attributes', to='sw_catalog.ItemAttributeValue', verbose_name='Значення'),
        ),
        migrations.AlterField(
            model_name='cartitemattribute',
            name='values',
            field=models.ManyToManyField(blank=True, to='sw_catalog.ItemAttributeValue', verbose_name='Значення'),
        ),
    ]
